name: "setup-python"
description: "Ensures to install a python version that's available on Anaconda"
inputs:
  python-version:
    description: "The python version to install (e.g. 3.7)"
    required: true
outputs:
  installed-python-version:
    description: "The installed python version"
    value: ${{ steps.fetch-python-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: get-python-version
      id: get-python-version
      shell: bash
      # We used to use `conda search python=3.x` to dynamically fetch the latest available version
      # in 3.x on Anaconda, but it turned out `conda search` is very slow (takes 40 ~ 50 seconds).
      # This overhead sums up to a significant amount of delay in the cross version tests
      # where we trigger more than 100 GitHub Actions runs.
      run: |
        python_version="${{ inputs.python-version }}"
        if [[ "$python_version" == "3.7" ]]; then
          python_version="3.7.12"
        elif [[ "$python_version" == "3.8" ]]; then
          python_version="3.8.12"
        else
          echo "Invalid python version: '$python_version'. Must be one of ['3.7', '3.8']"
          exit 1
        fi
        echo "::set-output name=version::$python_version"
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ steps.get-python-version.outputs.version }}
